describe('Login', () => {
  const user = Cypress.env('user_name')
  const password = Cypress.env('user_password')
  beforeEach(() => {
    cy.section('Pré-condições dos testes')
    cy.step('visita a aplicação em teste')
    cy.visit('/my-account/')
    cy.step('verifica que o título está correto')
    cy.title().should('be.equal', 'My Account – Automation Practice Site')
    cy.section('fim das pré-condições')
  })
  it('realiza login com username e password válidos', () => {
    cy.step('preeenche os campos "Username or e-mail Address" e "Password" e clica em "Login"')
    cy.gui_login()
  })
  context('login errors', () => {
    const invalid_user = 'douglas@vitor.com'
    const invalid_password = '@DougFanny123'

    it('realiza login com username inválido e password inválido', () => {
      cy.step('preenche o campo "Email address" com email inválido')
      cy.get('#username').type(invalid_user)
      cy.step('preenche o campo "Password" com senha inválida')
      cy.get('#password').type(invalid_password)
      cy.step('aguarda por 1 segundo')
      cy.wait(1000)
      cy.step('clica no botão "Login"')
      cy.get('input[value="Login"]').click()
      cy.step('verifica que a mensagem de erro está correta e visível')
      cy.contains('Error: A user could not be found with this email address.')
        .should('be.visible')
    })
    it('realiza login com username válido e campo password vazio', () => {
      cy.step('preenche o campo "Email address" com e-mail válido e deixa o campo "Password" vazio')
      cy.get('#username').type(user, { log: false})
      cy.step('aguarda por 1 segundo')
      cy.wait(1000)
      cy.step('clica no botão "Login"')
      cy.get('input[value="Login"]')
        .should('be.visible')
        .click()
      cy.step('verifica que a mensagem de erro está correta e visível')
      cy.contains('Error: Password is required.')
        .should('be.visible')
    })
    it('realiza login com o campo username vazio e password válido', () => {
      cy.step('preenche o campo "Password" com senha válida e deixa o campo "Email address" vazio')
      cy.get('#password').type(password, { log: false })
      cy.step('aguarda por 1 segundo')
      cy.wait(1000)
      cy.step('clica no botão "Login"')
      cy.get('input[value="Login"]')
        .should('be.visible')
        .click()
      cy.step('verifica que a mensagem de erro está correta e visível')
      cy.contains('Error: Username is required.')
        .should('be.visible')
    })
    it('realiza login com o campo username vazio e password vazio', () => {
      cy.step('aguarda por 1 segundo')
      cy.wait(1000)
      cy.step('clica no botão "Login"')
      cy.get('input[value="Login"]')
        .should('be.visible')
        .click()
      cy.step('verifica que a mensagem de erro está correta e visível')
      cy.contains('Error: Username is required.')
        .should('be.visible')
    })
  })
  context('especial cases', () => {
    const changed_user = Cypress.env('changed_user_name')
    const changed_password = Cypress.env('changed_password')
    const fake_password = '@FlaSiFu2023'

    it('a password da página de login deve estar mascarada com asteriscos', () => {
      cy.step('preenche o campo "Password" com alguns caracteres')
      cy.get('#password').type(fake_password)
      cy.step('verifica que a senha digitada está em asteriscos, portanto, não está visivel')
      cy.get('#password')
        .should('have.attr', 'type', 'password')
    })
    it('os campos password e username devem diferenciar maiúsculo e minúsculo', () => {
      cy.step('preeenche o campo "Email address" com a inicial em maiúsculo')
      cy.get('#username').type(changed_user, { log: false })
      cy.step('preenche o campo "Password" com a inicial em minúsculo')
      cy.get('#password').type(changed_password, { log: false })
      cy.step('aguarda por 1 segundo')
      cy.wait(1000)
      cy.step('clica no botão "Login"')
      cy.get('input[value="Login"]')
        .should('be.visible')
        .click()
      cy.step('verifica que a mensagem de erro está correta e visível')
      cy.contains('Error: the password you entered for the username Raffa@san.com is incorrect. Lost your password?')
        .should('be.visible')
    })
    it('realiza login e logout com sucesso e verifica que ao clicar em "voltar" no navegador, não deve estar logado', () => {
      cy.step('preeenche os campos "Username or e-mail Adress" e "Password" válidos e clica em "Login"')
      cy.gui_login()
      cy.step('aguarda por 2 segundos')
      cy.wait(2000)
      cy.step('clica em logout')
      cy.contains('a', 'Sign out')
        .should('be.visible')
        .click()
      cy.step('aguarda por 2 segundos')
      cy.wait(2000)
      cy.step('clica no botão "voltar" do navegador')
      cy.go('back')
      cy.get('input[name="login"]')
        .should('be.visible')
    })
  })
})
