describe('Shop', () => {
  beforeEach(() => {
    cy.section('Pré-condições dos testes')
    cy.step('visita a aplicação em teste')
    cy.visit('/shop/')
    cy.step('verifica que o título está correto')
    cy.title().should('be.equal', 'Products – Automation Practice Site')
    cy.section('fim das pré-condições')
  })
  it('shop filter - ajusta o filtro do preço do produto entre 150rps e 450rps', () => {
    cy.step('seleciona o seletor do preço minimo e verifica o valor')
    cy.get('#min_price')
      .invoke('val', [150])
      .trigger('input', { force: true })
      .should('have.value', '150')
    cy.step('verifica o seletor do preço maximo e verifica que o valor foi ajustado')
    cy.get('#max_price')
      .invoke('val', [150, 450])
      .trigger('input', { force: true })
      .should('have.value', '150,450')
  })
  it('shop Product - clica em um link de produto disponivel', () => {
    cy.step('verifica a quantidade de produtos disponíveis')
    cy.get('.woocommerce-LoopProduct-link')
      .should('have.length', 8)
      .should('be.visible')
    cy.step('clica no produto "Android Quick Start Guide" na categoria de produtos disponíveis')
    cy.contains('a', 'Android Quick Start Guide')
      .should('be.visible')
      .click()
    cy.step('verifica que o usuario foi redirecionado para a página que mostra apenas aquele produto específico')
    cy.url()
      .should('be.equal', `${Cypress.config('baseUrl')}product/android-quick-start-guide/`)
  })
  context('Shop - Default sorting funcionality', () => {
    it('classifica por "popularity" no menu suspenso de classificação padrão', () => {
      cy.step('clica no menu suspenso de classificação padrão e seleciona "popularity"')
      cy.get('select')
        .select('popularity')
        .should('be.visible')
        .and('contain', 'Sort by popularity')
    })
    it('classifica por "average rating" no menu suspenso de classificação padrão', () => {
      cy.step('clica no menu suspenso de classificação padrão e seleciona "average rating"')
      cy.get('select')
        .select('rating')
        .should('be.visible')
        .and('contain', 'Sort by average rating')
    })
    it('classifica por "newness" no menu suspenso de classificação padrão', () => {
      cy.step('clica no menu suspenso de classificação padrão e seleciona "newness"')
      cy.get('select')
        .select('date')
        .should('be.visible')
        .and('contain', 'Sort by newness')
    })

    it('classifica por "low to high" no menu suspenso de classificação padrão', () => {
      cy.step('clica no menu suspenso de classificação padrão e seleciona "low to high"')
      cy.get('select')
        .select('price')
        .should('be.visible')
        .and('contain', 'Sort by price: low to high')
    })
    it('classifica por "high to low" no menu suspenso de classificação padrão', () => {
      cy.step('clica no menu suspenso de classificação padrão e seleciona "high to low"')
      cy.get('select')
        .select('price-desc')
        .should('be.visible')
        .and('contain', 'Sort by price: high to low')
    })
  })
  context('Shop - Add to basket - View basket through item link', () => {
    beforeEach(() => {
      cy.step('clica em "ADD TO BASKET"')
      cy.contains('a', 'Add to basket')
        .should('be.visible')
        .click()
      cy.step('aguarda 2 segundos')
      cy.wait(2000)
      cy.step('clica em "View Basket"')
      cy.contains('a', 'View Basket')
        .should('be.visible')
        .click()
      cy.step('clica em "PROCEED TO CHECKOUT')
      cy.proceedToCheckout()
    })
    it('conclui uma compra utilizando o link "View Basquet" que direciona para a pagina de checkout', () => {
      cy.step('preenche os campos obrigatórios na página de checkout')
      cy.camposObrigatoriosEmCheckout()
      cy.step('seleciona método de pagamento "Direct Bank Transfer"')
      cy.get('#payment_method_bacs')
        .should('be.visible')
        .click()
      cy.step('clica em "PLACE ORDER"')
      cy.get('#place_order')
        .should('be.visible')
        .click()
      cy.step('verifica a mensagem de sucesso "Thank you. Your order has been received."')
      cy.get('.woocommerce-thankyou-order-received')
        .should('be.visible')
    })
    context('Shop - Tax', () => {
      it('verifica variações de taxa de imposto para a Índia em comparação com outros países', () => {
        cy.step('preenche os campos obrigatórios na página de checkout')
        cy.camposObrigatoriosEmCheckoutIndia()
        cy.step('verifica que a taxa para a India é de 2% do subtotal')
        cy.contains('.cart-subtotal', '350.00')
          .should('be.visible')
        cy.contains('.tax-rate', '7.00')
          .should('be.visible')
      })
    })
  })
})
