name: End-to-end tests
on: [push]
jobs:
  cypress-run-1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy cypress.env.json
        run: cp cypress/cypress.env.json cypress.env.json  
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:homePage

  cypress-run-2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy cypress.env.json
        run: cp cypress/cypress.env.json cypress.env.json  
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:login

  cypress-run-3:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy cypress.env.json
        run: cp cypress/cypress.env.json cypress.env.json  
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:myaccount

  cypress-run-4:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy cypress.env.json
        run: cp cypress/cypress.env.json cypress.env.json  
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:register

  cypress-run-5:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy cypress.env.json
        run: cp cypress/cypress.env.json cypress.env.json  
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:shop

        